In [8]:
import json
import requests
import time
from datetime import datetime as dt
from datetime import timedelta
# import pandas_ta as ta
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import ccxt
from tqdm import tqdm
from tvDatafeed import TvDatafeed, Interval

print(ccxt.__version__)

ftx = ccxt.ftx({'enableRateLimit':True})
binance = ccxt.binance({'enableRateLimit':True})
zm = ccxt.zipmex({'enableRateLimit':True})

API_HOST = 'https://api.bitkub.com'

1.64.7

In [588]:
def get_price_zm(sym):
    syms = sym +'/THB'
    return zm.fetch_ticker(syms)['close']


def get_thb():
    tv = TvDatafeed()
    symbols ='USDTHB'
    exchanges= 'GLOBALPRIME'
    timeframe = Interval.in_daily
    limit_bar =1
    df = tv.get_hist(symbol=symbols,exchange='OANDA',interval=timeframe,n_bars=limit_bar)
    return df['close'].values[0]

        
def bk_ticker(symbols='all'): 
    ''' symbols : List'''
    bit_kub_list = []
    all_res = {}
    req = '/api/market/ticker'
    url = API_HOST+req
    
    if symbols =='all':
        param ={'query':'all'}
        all_res = requests.get(url,params=param).json()

    else :
        for sym in symbols:
                syms= 'THB_'+ sym
                param ={'sym':syms}
    #             print(syms)
                try:
                    res = requests.get(url,params=param).json()
                    all_res.update(res)

                except Exception as e:
                    res= np.nan
                    all_res.update(res)
        return all_res

# OLD 
# def bk_ticker(symbols='all'): 
#     ''' symbols : List'''
#     bit_kub_list = []
#     all_res = {}

#     req = '/api/market/ticker'
#     url = API_HOST+req
#     if symbols =='all':
#         param ={'query':'all'}
#         all_res = requests.get(url,params=param).json()


#     else :
#         for i in symbols:
#             param ={'sym':i}
#             res = requests.get(url,params=param).json()
#             all_res.update(res)

In [590]:
bk_ticker(['CVC','BTC'])

{'THB_CVC': {'id': 14,
  'last': 8.68,
  'lowestAsk': 8.7,
  'highestBid': 8.68,
  'percentChange': -6.16,
  'baseVolume': 1032063.31021837,
  'quoteVolume': 9270914.06,
  'isFrozen': 0,
  'high24hr': 9.51,
  'low24hr': 8.45,
  'change': -0.57,
  'prevClose': 8.68,
  'prevOpen': 9.25},
 'THB_BTC': {'id': 1,
  'last': 1295937.95,
  'lowestAsk': 1295937.95,
  'highestBid': 1294002.11,
  'percentChange': -5.75,
  'baseVolume': 422.77937993,
  'quoteVolume': 554676650.72,
  'isFrozen': 0,
  'high24hr': 1376957.94,
  'low24hr': 1277038.01,
  'change': -79135.32,
  'prevClose': 1295937.95,
  'prevOpen': 1375073.27}}

In [502]:
## CCXT Function 
def get_data(ex,symbols,timeframe='1d'):
    # 
    
      df= pd.DataFrame(ex.fetch_ohlcv(symbols,timeframe),columns=['date','open','high','low','close','volume'])
#       data.drop(columns='volume',inplace=True)
      df['date']=df['date'].apply(ex.iso8601)
      df['date']=pd.to_datetime(df['date'])
    #   df['date']=df['date'].apply(lambda x: x.strftime('%Y-%m-%d %H:%M'))
    #   df['date']=pd.to_datetime(df['date'])
    #   df.dropna(inplace=True)

      df.set_index('date',inplace=True)
      return df




def order_book(exchange,symbol):
    try:
        res = exchange.fetchOrderBook(symbol)
        ex_name = exchange.name
        if ex_name == 'Zipmex' :
            # check size data bid ,ask and set to equal
                min_data = min(len(res['bids']), len(res['asks']))
                res['bids']  = res['bids'][:min_data]
                res['asks']  = res['bids'][:min_data]
        order_book = pd.DataFrame(res)
        b_size = [order_book['bids'][i][1] for i in range(len(order_book))]
        order_book['bids_size'] = b_size

        b_price =  [order_book['bids'][i][0] for i in range(len(order_book))]
        order_book['bids_price'] = b_price


        a_size = [order_book['asks'][i][1] for i in range(len(order_book))]
        a_price  = [order_book['asks'][i][0] for i in range(len(order_book))]
        order_book['asks_size'] = a_size
        order_book['asks_price'] = a_price


        order_book = order_book[['bids_price','bids_size','asks_price','asks_size']]
        order_book['value_bid'] = order_book['bids_price'] * order_book['bids_size']
        order_book['value_ask'] = order_book['asks_price'] * order_book['asks_size']
        bid = order_book['bids_price'][0]
        offer = order_book['asks_price'][0]
        res =exchange.fetch_ticker(symbol)
        last = res['last']
        asks=  res['ask']
        bids = res['bid']
        spread = (asks/bids) -1 # asks/bids -1 , (offer -bid) /offer
        spread_offer = last/offer -1
        spread_bid =bid/last -1

        ts=  dt.now()
    #     print(f' [{ts}] [{symbol}]  {bid} : {offer}  Spread @ {spread*100:.2f}%: Last{last}')
    #     print(f' [{ts}] [{symbol}]  Spread Bid{spread_bid*100:.2f} %   offer{spread_offer*100 :.2f} % ')
    except Exception as e:
        print(str(e))
        order_book = pd.DataFrame()
        order_book['bids_price'] = [np.nan]
        order_book['asks_price'] = [np.nan]
    return order_book

In [503]:
order_book(ftx,'XLM/USD')

ftx does not have market symbol XLM/USD

   bids_price  asks_price
0         NaN         NaN

In [201]:
def get_price_spread(exchange,name_list,end_symbol_str):

    ''' exchange =ccxt.ExchangeClass
        name_sym ['list'] = symbol name'''
    data = []
    ex_name = exchange.name 
    for name_sym in name_list:
        symbols= name_sym +'/'+end_symbol_str
        try:
            res= exchange.fetch_ticker(symbols)
            last = res['last']
            ask = res['ask']
            bid = res['bid']
            volume= res['quoteVolume']
            spread=  ((ask-bid) / ask)*100
        except Exception as e:
            res= []
            print(str(e))


    
#         if last >=1 :
        if res != []:
            dict_a = {'exchange':ex_name,'symbol':symbols,'name':name_sym,'last':last,'volume':volume,'bid':bid,'ask':ask,'spread':spread}
            data.append(dict_a)
        else :
            print('ERROR')
    return data
print(get_price_spread(zm,['DODO'],'USD'))

zipmex does not have market symbol DODO/USD
ERROR
[]

# Compare Price 2 Exchange

In [175]:
# Get data from zipmex exchange and compare usdthb realtime rate
sym_list = ['SOL','LUNA','ETH','FTT','BTC']
data = get_price_spread(zm,sym_list,'THB')
thb_usd = get_thb()

# convert symbol/thb to symbol/USD
for data_ in data :
    data_['last_usd'] = (data_['last'])/thb_usd 
    print(data_)

WARNING:tvDatafeed.main:you are using nologin method, data you access may be limited

{'exchange': 'Zipmex', 'symbol': 'SOL/THB', 'name': 'SOL', 'last': 2921.2, 'volume': 6229669.4337, 'bid': 2907.54, 'ask': 2916.19, 'spread': 0.2966199047387204, 'last_usd': 89.6183580807461}
{'exchange': 'Zipmex', 'symbol': 'LUNA/THB', 'name': 'LUNA', 'last': 2812.05, 'volume': 15130802.2378, 'bid': 2799.32, 'ask': 2809.74, 'spread': 0.37085281912204043, 'last_usd': 86.26978770401277}
{'exchange': 'Zipmex', 'symbol': 'ETH/THB', 'name': 'ETH', 'last': 87187.81, 'volume': 20372726.646739, 'bid': 87025.05, 'ask': 87174.46, 'spread': 0.1713919420894646, 'last_usd': 2674.800895815438}
{'exchange': 'Zipmex', 'symbol': 'FTT/THB', 'name': 'FTT', 'last': 1348.29, 'volume': 358871.90971, 'bid': 1339.22, 'ask': 1343.28, 'spread': 0.30224525043177486, 'last_usd': 41.363664253282614}
{'exchange': 'Zipmex', 'symbol': 'BTC/THB', 'name': 'BTC', 'last': 1287296.05, 'volume': 54734744.12840931, 'bid': 1286000.0, 'ask': 1286849.42, 'spread': 0.066007722954868, 'last_usd': 39492.454595655916}

In [176]:
# Dict to DataFrame
df_zm = pd.DataFrame(data)
# delete thb bath columns
df_zm['last'] = df_zm['last_usd']
df_zm.drop(columns='last_usd',inplace=True)
df_zm

,exchange,symbol,name,last,volume,bid,ask,spread
0,Zipmex,SOL/THB,SOL,89.618358,6.229669e+06,2907.54,2916.19,0.296620
1,Zipmex,LUNA/THB,LUNA,86.269788,1.513080e+07,2799.32,2809.74,0.370853
2,Zipmex,ETH/THB,ETH,2674.800896,2.037273e+07,87025.05,87174.46,0.171392
3,Zipmex,FTT/THB,FTT,41.363664,3.588719e+05,1339.22,1343.28,0.302245
4,Zipmex,BTC/THB,BTC,39492.454596,5.473474e+07,1286000.00,1286849.42,0.066008

In [177]:
ftx_data = get_price_spread(ftx,df_zm.name.to_list(),'USD')
df_ftx= pd.DataFrame(ftx_data)
df_ftx

,exchange,symbol,name,last,volume,bid,ask,spread
0,FTX,SOL/USD,SOL,88.075,1.148408e+08,88.0475,88.070,0.025548
1,FTX,LUNA/USD,LUNA,84.920,5.930040e+06,84.7600,84.880,0.141376
2,FTX,ETH/USD,ETH,2635.500,3.354139e+08,2635.4000,2635.600,0.007588
3,FTX,FTT/USD,FTT,40.590,3.604002e+07,40.5860,40.597,0.027096
4,FTX,BTC/USD,BTC,38920.000,6.060934e+08,38919.0000,38920.000,0.002569

In [412]:
# Merge Dataframe
m_df  =pd.merge(df_zm, df_ftx, on=['name'],suffixes=['_zipmex','_ftx']).dropna()
# m_df['last_zipmex'] =  m_df['last_usd']
m_df = m_df[['name','last_zipmex','last_ftx']]
m_df['diff_pct']=(m_df['last_ftx'] - m_df['last_zipmex']) /m_df['last_zipmex']
m_df

   name   last_zipmex   last_ftx  diff_pct
0   SOL     89.618358     88.075 -0.017221
1  LUNA     86.269788     84.920 -0.015646
2   ETH   2674.800896   2635.500 -0.014693
3   FTT     41.363664     40.590 -0.018704
4   BTC  39492.454596  38920.000 -0.014495

In [183]:
# Single symbol
fast_view(i,debug= True)

SOLTHB
 Zipmex 41.16855 Binance 40.68000 1.20%
 Zipmex 41.16855 FTX 40.69400  1.17%
 FTX 40.69400 Binance 40.68000  0.03%
 BITKUB 41.36121 Binance 40.68000  1.67%
 BITKUB 41.36121 FTX 40.69400  1.64%
 BITKUB 41.36121 Zipmex 41.16855  0.47%

  symbol    zipmex  binance     ftx    bk_usd
0    FTT  41.16855    40.68  40.694  41.36121

In [144]:
# ALL DATA FROM SYMBOLS LIST
all_df

  symbol      zipmex    binance          ftx      bk_usd
0    BNB   383.75874   379.0000   378.851000   384.74567
0    ETH  2687.05792  2651.9400  2651.800000  2690.51417
0    SOL    89.72941    88.6700    88.657500    89.63983
0    XRP     0.74150     0.7321     0.731975     0.74212
0    LTC   104.44416   103.2000   103.130000   104.38152
0    FTT    41.30415    40.8100    40.800000    41.29863

# Compare FEE BITKUB,ZIPMEX

In [238]:
path = r'C:\Users\User\Desktop\fee.xlsx'
zm_fee = pd.read_excel(path, sheet_name='zipmex')
zm_fee['name'] =zm_fee[zm_fee.columns[0]].str.split().str[0]
zm_fee['fee'] =zm_fee[zm_fee.columns[1]].str.split().str[0]
zm_fee['exchange'] = 'Zipmex'
# Delete ['สินทรัพย์/โทเคน, ธรรมเนียม columns	']
zm_fee = zm_fee.iloc[:,2:]

zm_fee.tail(1)

    name   fee exchange
42  YLDY  1300   Zipmex

In [250]:
# Get data from name list


zm_fee['symbol_name'] =zm_fee['name'] +'/THB'
price_list = []
for i in zm_fee['symbol_name'].to_list():
    last=  (zm.fetch_ticker(i)['last'])
    price_list.append(last)
zm_fee['last']  = price_list    

zm_fee['last'] = zm_fee['last'].round(3)
zm_fee['fee'] = zm_fee['fee'].astype('float')
zm_fee['value'] =zm_fee['last'] *zm_fee['fee'] 
# zm_fee['last'] = zm_fee['name'].apply(get_price_zm)
# zm_fee['value'] =zm_fee['last'] *zm_fee['fee'] 
zm_fee.dropna().to_csv('zm_df.csv')

In [253]:
zm_fee

     name         fee exchange symbol_name         last        value
0     BTC     0.00050   Zipmex     BTC/THB  1291888.940   645.944470
1     ETH     0.01500   Zipmex     ETH/THB    87282.000  1309.230000
2     LTC     0.02500   Zipmex     LTC/THB     3399.904    84.997600
3     XRP     0.50000   Zipmex     XRP/THB       24.210    12.105000
4     BCH     0.00500   Zipmex     BCH/THB     9584.520    47.922600
5    USDT    25.00000   Zipmex    USDT/THB       33.100   827.500000
6    GOLD     0.30000   Zipmex    GOLD/THB     2094.990   628.497000
7    USDC    25.00000   Zipmex    USDC/THB       33.109   827.725000
8    LINK     0.50000   Zipmex    LINK/THB      459.928   229.964000
9     C8P    15.00000   Zipmex     C8P/THB       39.800   597.000000
10    ENJ    20.00000   Zipmex     ENJ/THB       46.360   927.200000
11    OMG     3.00000   Zipmex     OMG/THB      129.831   389.493000
12    YFI     0.00045   Zipmex     YFI/THB   662988.460   298.344807
13    MKR     0.00700   Zipmex     MKR/THB    60000.010   420.000070
14    SXP     7.00000   Zipmex     SXP/THB       45.200   316.400000
15    ZMT    20.00000   Zipmex     ZMT/THB       93.050  1861.000000
16   COMP     0.06200   Zipmex    COMP/THB     3571.380   221.425560
17   SAND    15.00000   Zipmex    SAND/THB       98.314  1474.710000
18    XLM     0.02000   Zipmex     XLM/THB        5.797     0.115940
19    SIX     1.00000   Zipmex     SIX/THB        5.000     5.000000
20    AXS     0.82000   Zipmex     AXS/THB     1671.090  1370.293800
21    TOK   150.00000   Zipmex     TOK/THB        1.490   223.500000
22  MATIC     0.10000   Zipmex   MATIC/THB       49.292     4.929200
23   AAVE     0.13000   Zipmex    AAVE/THB     4091.990   531.958700
24    HOT  2128.00000   Zipmex     HOT/THB        0.137   291.536000
25    SNX     3.33000   Zipmex     SNX/THB      120.172   400.172760
26    BAT    27.00000   Zipmex     BAT/THB       21.892   591.084000
27    FTT     0.46000   Zipmex     FTT/THB     1344.990   618.695400
28    UNI     0.82000   Zipmex     UNI/THB      295.288   242.136160
29  1INCH     6.91000   Zipmex   1INCH/THB       44.370   306.596700
30    CHZ    62.00000   Zipmex     CHZ/THB        6.949   430.838000
31    CRV     9.47000   Zipmex     CRV/THB       74.004   700.817880
32    ZRX    21.00000   Zipmex     ZRX/THB       16.392   344.232000
33    BNT     5.47000   Zipmex     BNT/THB       73.418   401.596460
34    KNC     4.00000   Zipmex     KNC/THB       79.114   316.456000
35   BAND     2.97000   Zipmex    BAND/THB      125.214   371.885580
36  ALPHA    24.00000   Zipmex   ALPHA/THB       10.096   242.304000
37   AFIN   100.00000   Zipmex    AFIN/THB        2.060   206.000000
38   GALA   150.00000   Zipmex    GALA/THB        7.407  1111.050000
39  SUSHI    10.00000   Zipmex   SUSHI/THB      101.459  1014.590000
40    GRT    90.00000   Zipmex     GRT/THB       11.173  1005.570000
41    SLP   800.00000   Zipmex     SLP/THB        0.641   512.800000
42   YLDY  1300.00000   Zipmex    YLDY/THB        0.150   195.000000

In [591]:
# bitkub Fee rate 
fee_kub = pd.read_excel(path, sheet_name='bitkub')

fee_kub['name'] =fee_kub[fee_kub.columns[0]].str.split('(').str[1].str.split(')').str[0]
fee_kub['fee'] =fee_kub[fee_kub.columns[2]].str.split().str[0]
fee_kub['exchange'] ='bitkub'
fee_kub = fee_kub.iloc[:,4:][0:10]
# fee_kub['last'] =fee_kub['name'].apply(bk_ticker)
fee_kub

   name          fee exchange
0   CVC  90.00000000   bitkub
1   BSV       0.0004   bitkub
2   ETH   0.00625000   bitkub
3   KUB         0.01   bitkub
4  COMP   0.21000000   bitkub
5   CRV   8.71000000   bitkub
6   AXS   0.56000000   bitkub
7  SAND   7.34000000   bitkub
8   XRP         0.25   bitkub
9  LINK   1.67000000   bitkub

In [592]:
fee_kub['last'] =fee_kub['name'].to_list().apply(bk_ticker)

AttributeError: 'list' object has no attribute 'apply'

In [598]:
ll = fee_kub['name'].to_list()
data = bk_ticker(ll)
price_datas
for i in data:
    price_data = data[i]['last']

In [568]:
import math

# get data last from dic
fee_kub['last_n'] = 0
for i in range(len(fee_kub)):
    if (fee_kub['last'].iloc[i]) != {}:
#     if not math.isnan(fee_kub['last'].iloc[i]):
        lp = (fee_kub['last'].iloc[i]['last'])
        fee_kub['last_n'].iloc[i] = lp
#         print(i,lp)
    else:
        fee_kub['last_n'].iloc[i] = np.nan
        
fee_kub['last'] = fee_kub['last_n']
fee_kub.drop(columns='last_n',inplace=True)
fee_kub[['last','fee']] = fee_kub[['last','fee']].astype(float)
fee_kub['last']  = fee_kub['last'].round(3)
fee_kub['value'] = fee_kub['last'] * fee_kub['fee']


# fee_kub =fee_kub.sort_values('value',ascending=False).dropna()
fee_kub =fee_kub.dropna()

C:\Users\User\AppData\Roaming\Python\Python37\site-packages\pandas\core\indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)

In [546]:
fee_kub

     name        fee exchange         last        value
0     CVC   90.00000   bitkub        8.700   783.000000
2     ETH    0.00625   bitkub    87507.770   546.923563
3     KUB    0.01000   bitkub      269.200     2.692000
4    COMP    0.21000   bitkub     3597.510   755.477100
5     CRV    8.71000   bitkub       74.350   647.588500
6     AXS    0.56000   bitkub     1674.000   937.440000
7    SAND    7.34000   bitkub       98.650   724.091000
8     XRP    0.25000   bitkub       24.250     6.062500
9    LINK    1.67000   bitkub      462.420   772.241400
10    KNC    4.00000   bitkub       79.380   317.520000
11    XLM    0.02000   bitkub        5.810     0.116200
12    SIX    1.00000   bitkub        5.085     5.085000
14  ALPHA   70.00000   bitkub       10.110   707.700000
15    BAL    2.20000   bitkub      382.360   841.192000
16    LTC    0.00100   bitkub     3408.100     3.408100
17   IOST    1.00000   bitkub        0.760     0.760000
19   NEAR    0.01000   bitkub      349.650     3.496500
20   AAVE    0.28000   bitkub     4109.000  1150.520000
22   JFIN    5.75000   bitkub       56.560   325.220000
23    BAT   32.00000   bitkub       22.020   704.640000
24    ZIL    0.20000   bitkub        1.302     0.260400
25    DOT    0.10000   bitkub      562.240    56.224000
26  SUSHI    6.61000   bitkub      101.480   670.782800
27    BCH    0.00100   bitkub     9606.000     9.606000
28    ADA    1.00000   bitkub       28.630    28.630000
29    BNB    0.00100   bitkub    12575.000    12.575000
30    POW   48.00000   bitkub       17.390   834.720000
31   SCRT    0.10000   bitkub      151.220    15.122000
32    YFI    0.00110   bitkub   663473.690   729.821059
33    BTC    0.00050   bitkub  1294999.990   647.499995
34    OMG    5.75000   bitkub      130.480   750.260000
35   USDT   35.00000   bitkub       33.010  1155.350000
36   DOGE    5.00000   bitkub        4.090    20.450000
37   USDC   35.00000   bitkub       32.940  1152.900000
38    MKR    0.01200   bitkub    60435.050   725.220600
39    ENJ   15.00000   bitkub       46.510   697.650000
40    KSM    0.01000   bitkub     4046.650    40.466500
42    WAN    0.10000   bitkub       17.590     1.759000
43    SNT  535.00000   bitkub        1.770   946.950000
44    ZRX   43.00000   bitkub       16.460   707.780000
45    ABT   35.00000   bitkub        4.310   150.850000
46   MANA    9.98000   bitkub       83.480   833.130400
47    DAI   15.00000   bitkub       33.150   497.250000
48   BAND    0.01000   bitkub      126.800     1.268000
49    GLM   75.00000   bitkub       15.950  1196.250000
50    UNI    2.58000   bitkub      297.090   766.492200
51    FTT    0.63000   bitkub     1348.660   849.655800
52  OCEAN   39.00000   bitkub       14.640   570.960000
53    SNX    7.05000   bitkub      120.130   846.916500
55   GALA  143.00000   bitkub        7.450  1065.350000
56     GT    9.50000   bitkub      220.000  2090.000000
58     GF   10.00000   bitkub       50.800   508.000000
59    IMX    8.10000   bitkub       42.340   342.954000
60    ENS    1.47000   bitkub      496.400   729.708000
61   DYDX   13.00000   bitkub      169.070  2197.910000
62    ILV    0.04600   bitkub    17511.910   805.547860
68   LYXE    1.50000   bitkub      445.000   667.500000
76    SOL    0.01000   bitkub     2929.990    29.299900
77   AVAX    0.01000   bitkub     2541.180    25.411800

In [547]:
m_df2 = pd.merge(zm_fee,fee_kub,on=['name'],suffixes=['_zm','_bk'])
m_df2

,name,fee_zm,exchange_zm,symbol_name,last_zm,value_zm,fee_bk,exchange_bk,last_bk,value_bk
0,BTC,0.00050,Zipmex,BTC/THB,1291888.940,645.944470,0.00050,bitkub,1294999.990,647.499995
1,ETH,0.01500,Zipmex,ETH/THB,87282.000,1309.230000,0.00625,bitkub,87507.770,546.923563
2,LTC,0.02500,Zipmex,LTC/THB,3399.904,84.997600,0.00100,bitkub,3408.100,3.408100
3,XRP,0.50000,Zipmex,XRP/THB,24.210,12.105000,0.25000,bitkub,24.250,6.062500
4,BCH,0.00500,Zipmex,BCH/THB,9584.520,47.922600,0.00100,bitkub,9606.000,9.606000
5,USDT,25.00000,Zipmex,USDT/THB,33.100,827.500000,35.00000,bitkub,33.010,1155.350000
6,USDC,25.00000,Zipmex,USDC/THB,33.109,827.725000,35.00000,bitkub,32.940,1152.900000
7,LINK,0.50000,Zipmex,LINK/THB,459.928,229.964000,1.67000,bitkub,462.420,772.241400
8,ENJ,20.00000,Zipmex,ENJ/THB,46.360,927.200000,15.00000,bitkub,46.510,697.650000
9,OMG,3.00000,Zipmex,OMG/THB,129.831,389.493000,5.75000,bitkub,130.480,750.260000
10,YFI,0.00045,Zipmex,YFI/THB,662988.460,298.344807,0.00110,bitkub,663473.690,729.821059
11,MKR,0.00700,Zipmex,MKR/THB,60000.010,420.000070,0.01200,bitkub,60435.050,725.220600
12,COMP,0.06200,Zipmex,COMP/THB,3571.380,221.425560,0.21000,bitkub,3597.510,755.477100
13,SAND,15.00000,Zipmex,SAND/THB,98.314,1474.710000,7.34000,bitkub,98.650,724.091000
14,XLM,0.02000,Zipmex,XLM/THB,5.797,0.115940,0.02000,bitkub,5.810,0.116200
15,SIX,1.00000,Zipmex,SIX/THB,5.000,5.000000,1.00000,bitkub,5.085,5.085000
16,AXS,0.82000,Zipmex,AXS/THB,1671.090,1370.293800,0.56000,bitkub,1674.000,937.440000
17,AAVE,0.13000,Zipmex,AAVE/THB,4091.990,531.958700,0.28000,bitkub,4109.000,1150.520000
18,SNX,3.33000,Zipmex,SNX/THB,120.172,400.172760,7.05000,bitkub,120.130,846.916500
19,BAT,27.00000,Zipmex,BAT/THB,21.892,591.084000,32.00000,bitkub,22.020,704.640000
20,FTT,0.46000,Zipmex,FTT/THB,1344.990,618.695400,0.63000,bitkub,1348.660,849.655800
21,UNI,0.82000,Zipmex,UNI/THB,295.288,242.136160,2.58000,bitkub,297.090,766.492200
22,CRV,9.47000,Zipmex,CRV/THB,74.004,700.817880,8.71000,bitkub,74.350,647.588500
23,ZRX,21.00000,Zipmex,ZRX/THB,16.392,344.232000,43.00000,bitkub,16.460,707.780000
24,KNC,4.00000,Zipmex,KNC/THB,79.114,316.456000,4.00000,bitkub,79.380,317.520000
25,BAND,2.97000,Zipmex,BAND/THB,125.214,371.885580,0.01000,bitkub,126.800,1.268000
26,ALPHA,24.00000,Zipmex,ALPHA/THB,10.096,242.304000,70.00000,bitkub,10.110,707.700000
27,GALA,150.00000,Zipmex,GALA/THB,7.407,1111.050000,143.00000,bitkub,7.450,1065.350000
28,SUSHI,10.00000,Zipmex,SUSHI/THB,101.459,1014.590000,6.61000,bitkub,101.480,670.782800

In [548]:
# quick view

def fast_view(name_sym:str,debug=True):
    ''' Compare Symbols on sym_list  multi exchange ['FTX , BINANCE , ZIPMEX ,BITKUB']''' 

    # Call price frome 
    p1=order_book(ftx,name_sym+'/USD')
    p2=order_book(binance,name_sym+'/USDT')
    p3= order_book(zm,name_sym+'/THB')
    
    bk_sym = [name_sym]

    p4 =  bk_ticker(bk_sym)


    #  get first bid from orderbook
    # display(p3.iloc[[0]],p2.iloc[[0]],p1.iloc[[0]])
    zm_usd  =float(round((p3.iloc[[0]]['asks_price'].values[0] / usd_thb),5)) #
    ftx_usd = p1.iloc[[0]]['asks_price'].values[0]
    bn_usd = p2.iloc[[0]]['asks_price'].values[0]
    if p4 != {}:
        bk_usd = float(round(p4['last'] / usd_thb,5))

    else:
        bk_usd = np.nan


    diff = (zm_usd/bn_usd)-1
    diff2 = (zm_usd/ftx_usd)-1
    diff3 = (ftx_usd/bn_usd)-1

    diff4 = (bk_usd/bn_usd)-1
    diff5 = (bk_usd/ftx_usd)-1
    diff6 = (bk_usd/zm_usd)-1
    if debug:
        print(symbol)
        print(f' Zipmex {zm_usd:.5f} Binance {bn_usd:.5f} {diff*100:.2f}%')
        print(f' Zipmex {zm_usd:.5f} FTX {ftx_usd:.5f}  {diff2*100:.2f}%')
        print(f' FTX {ftx_usd:.5f} Binance {bn_usd:.5f}  {diff3*100:.2f}%')
        print(f' BITKUB {bk_usd:.5f} Binance {bn_usd:.5f}  {diff4*100:.2f}%')
        print(f' BITKUB {bk_usd:.5f} FTX {ftx_usd:.5f}  {diff5*100:.2f}%')
        print(f' BITKUB {bk_usd:.5f} Zipmex {zm_usd:.5f}  {diff6*100:.2f}%')
    dict_data= {'symbol':name_sym,'zipmex':zm_usd,'binance':bn_usd,'ftx':ftx_usd,'bk_usd':bk_usd}
    return pd.DataFrame([dict_data])

In [549]:
m_df2 = m_df2.set_index('name').drop(['USDT','USDC'])
m_df2

,fee_zm,exchange_zm,symbol_name,last_zm,value_zm,fee_bk,exchange_bk,last_bk,value_bk
name,,,,,,,,,
BTC,0.00050,Zipmex,BTC/THB,1291888.940,645.944470,0.00050,bitkub,1294999.990,647.499995
ETH,0.01500,Zipmex,ETH/THB,87282.000,1309.230000,0.00625,bitkub,87507.770,546.923563
LTC,0.02500,Zipmex,LTC/THB,3399.904,84.997600,0.00100,bitkub,3408.100,3.408100
XRP,0.50000,Zipmex,XRP/THB,24.210,12.105000,0.25000,bitkub,24.250,6.062500
BCH,0.00500,Zipmex,BCH/THB,9584.520,47.922600,0.00100,bitkub,9606.000,9.606000
LINK,0.50000,Zipmex,LINK/THB,459.928,229.964000,1.67000,bitkub,462.420,772.241400
ENJ,20.00000,Zipmex,ENJ/THB,46.360,927.200000,15.00000,bitkub,46.510,697.650000
OMG,3.00000,Zipmex,OMG/THB,129.831,389.493000,5.75000,bitkub,130.480,750.260000
YFI,0.00045,Zipmex,YFI/THB,662988.460,298.344807,0.00110,bitkub,663473.690,729.821059
MKR,0.00700,Zipmex,MKR/THB,60000.010,420.000070,0.01200,bitkub,60435.050,725.220600
COMP,0.06200,Zipmex,COMP/THB,3571.380,221.425560,0.21000,bitkub,3597.510,755.477100
SAND,15.00000,Zipmex,SAND/THB,98.314,1474.710000,7.34000,bitkub,98.650,724.091000
XLM,0.02000,Zipmex,XLM/THB,5.797,0.115940,0.02000,bitkub,5.810,0.116200
SIX,1.00000,Zipmex,SIX/THB,5.000,5.000000,1.00000,bitkub,5.085,5.085000
AXS,0.82000,Zipmex,AXS/THB,1671.090,1370.293800,0.56000,bitkub,1674.000,937.440000
AAVE,0.13000,Zipmex,AAVE/THB,4091.990,531.958700,0.28000,bitkub,4109.000,1150.520000
SNX,3.33000,Zipmex,SNX/THB,120.172,400.172760,7.05000,bitkub,120.130,846.916500
BAT,27.00000,Zipmex,BAT/THB,21.892,591.084000,32.00000,bitkub,22.020,704.640000
FTT,0.46000,Zipmex,FTT/THB,1344.990,618.695400,0.63000,bitkub,1348.660,849.655800
UNI,0.82000,Zipmex,UNI/THB,295.288,242.136160,2.58000,bitkub,297.090,766.492200
CRV,9.47000,Zipmex,CRV/THB,74.004,700.817880,8.71000,bitkub,74.350,647.588500
ZRX,21.00000,Zipmex,ZRX/THB,16.392,344.232000,43.00000,bitkub,16.460,707.780000
KNC,4.00000,Zipmex,KNC/THB,79.114,316.456000,4.00000,bitkub,79.380,317.520000
BAND,2.97000,Zipmex,BAND/THB,125.214,371.885580,0.01000,bitkub,126.800,1.268000
ALPHA,24.00000,Zipmex,ALPHA/THB,10.096,242.304000,70.00000,bitkub,10.110,707.700000
GALA,150.00000,Zipmex,GALA/THB,7.407,1111.050000,143.00000,bitkub,7.450,1065.350000
SUSHI,10.00000,Zipmex,SUSHI/THB,101.459,1014.590000,6.61000,bitkub,101.480,670.782800

In [551]:

name_sym =['BNB','ETH','SOL','XRP','LTC','FTT']



all_df2 = pd.DataFrame()
for  i in m_df2.index.to_list():
    print(i)
    df=  fast_view(i,debug= False)
    all_df2  = all_df2.append(df)
all_df2

BTC
ETH
LTC
XRP
BCH
LINK
ENJ
OMG
YFI
MKR
COMP
SAND
XLM
ftx does not have market symbol XLM/USD
SIX
ftx does not have market symbol SIX/USD
binance does not have market symbol SIX/USDT
AXS
AAVE
SNX
BAT
FTT
UNI
CRV
ZRX
KNC
BAND
ALPHA
GALA
SUSHI

In [553]:
all_df2

  symbol       zipmex      binance           ftx       bk_usd
0    BTC  39644.23641  39160.27000  39165.000000  39728.80077
0    ETH   2683.51423   2650.64000   2650.700000   2684.64413
0    LTC    104.63861    103.40000    103.390000    104.55577
0    XRP      0.74405      0.73500      0.734900      0.74396
0    BCH    293.89772    290.40000    290.500000    294.69874
0   LINK     14.14537     14.03000     14.032000     14.19377
0    ENJ      1.42650      1.41100      1.411400      1.42686
0    OMG      4.00086      3.95800      3.958500      4.00295
0    YFI  20243.87624  20028.20000  20025.000000  20354.45116
0    MKR   1853.33783   1834.00000   1836.500000   1854.06338
0   COMP    109.85550    108.70000    108.690000    110.36661
0   SAND      3.02290      2.99020      2.991150      3.02644
0    XLM      0.17841      0.17630           NaN      0.17824
0    SIX      0.15462          NaN           NaN      0.15600
0    AXS     51.20229     50.69000     50.693000     51.35599
0   AAVE    125.32857    124.00000    124.160000    126.05841
0    SNX      3.68696      3.64800      3.647500      3.68542
0    BAT      0.67440      0.66770      0.668275      0.67554
0    FTT     41.37962     40.92000     40.912000     41.37502
0    UNI      9.10145      9.02000      9.016000      9.11431
0    CRV      2.27666      2.25100      2.253050      2.28218
0    ZRX      0.50323      0.49790      0.498250      0.50497
0    KNC      2.42759      2.39700      2.400700      2.43159
0   BAND      3.89119      3.85200      3.853000      3.89005
0  ALPHA      0.30887      0.30580      0.305500      0.31047
0   GALA      0.22808      0.22571      0.225750      0.22886
0  SUSHI      3.11195      3.07800      3.078400      3.11327

# Test

In [504]:
fast_view('XLM',debug= False)

ftx does not have market symbol XLM/USD

  symbol   zipmex  binance  ftx   bk_usd
0    XLM  0.17844   0.1764  NaN  0.17916

In [565]:
p4= bk_ticker(['BTC'])
p4['last']

1294000

In [499]:
order_book(ftx,'XLM')

ftx does not have market symbol XLM

   bid
0  NaN